server:
  port: ${SERVER_PORT:8060}
spring:
  application:
     name: message
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS_KAFKA:localhost:9094}
    consumer:
      group-id: ${GROUP_ID_KAFKA:order-group-id}
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:demospringemail6@gmail.com}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
management:
  health:
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
app:
  kafka:
    topics:
      message-success: ${TOPIC_MESSAGE_SUCCESS:message.success.v1}
    trusted: ${KAFKA_TRUSTED_PACKAGE:com.ilyaproject.*}
  mail:
    sender: ${APP_MAIL_SENDER:demospringemail6@gmail.com}
    recipient: ${APP_MAIL_RECIPIENT:mishamazbelazkamaz@gmail.com}