global:
  storageClass: hostpath

kraft:
  enabled: true

volumePermissions:
  enabled: true

controller:
  replicaCount: 1
  persistence:
    enabled: true
    size: 5Gi
  config:
    process.roles: "controller"
    controller.listener.names: "CONTROLLER"
    listeners: "CONTROLLER://:9093"
    listener.security.protocol.map: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
    controller.quorum.voters: "0@kafka-controller-0.kafka-controller-headless.default.svc.cluster.local:9093"
  resources:
    requests:
      memory: 512Mi
    limits:
      memory: 768Mi


broker:
  replicaCount: 1
  persistence:
    enabled: true
    size: 1Gi
  config:
    process.roles: "broker"
    listeners: "PLAINTEXT://:9092"
    inter.broker.listener.name: "PLAINTEXT"
    listener.security.protocol.map: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
    controller.quorum.bootstrap.servers: "kafka-controller-0.kafka-controller-headless.default.svc.cluster.local:9093"
    controller.listener.names: "CONTROLLER"
    offsets.topic.replication.factor: 1
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "1"
      memory: 1500Mi


service:
  type: ClusterIP


listeners:
  client:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT


config:
  log.retention.hours: "168"
  log.segment.bytes: "1073741824"
  log.retention.check.interval.ms: "300000"