server:
  port: ${SERVER_PORT:8090}
spring:
  application:
    name: "order"
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5431/orderdb}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  grpc:
    server:
      port: ${GRPC_SERVER_PORT:9091}
    client:
      channels:
        catalog:
          address: ${CATALOG_GRPC_ADDR:0.0.0.0:9090}
          negotiationType: ${CATALOG_GRPC_NEGOTIATION:PLAINTEXT}
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS_KAFKA:localhost:9094}
    consumer:
      group-id: ${GROUP_ID_KAFKA:order-group-id}
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
app:
  kafka:
    topics:
      payment-succeeded: ${TOPIC_PAYMENT_SUCCEEDED:payments.succeeded.v1}
      payment-failed: ${TOPIC_PAYMENT_FAILED:payments.failed.v1}
    trusted: ${KAFKA_TRUSTED_PACKAGE:com.ilyaproject.*}