server:
  port: 8090
spring:
  application:
    name: "order"
  datasource:
    url: "jdbc:postgresql://localhost:5431/orderdb"
    username: admin
    password: admin
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  grpc:
    client:
      channels:
        catalog:
          address: 0.0.0.0:9090
management:
  endpoints:
    web:
      exposure:
        include: "*"

