server:
  port: ${SERVER_PORT:8090}
spring:
  application:
    name: "order"
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5431/orderdb}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  grpc:
    server:
      port: ${GRPC_SERVER_PORT:9091}
    client:
      channels:
        catalog:
          address: ${CATALOG_GRPC_ADDR:0.0.0.0:9090}
          negotiationType: ${CATALOG_GRPC_NEGOTIATION:PLAINTEXT}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true

