spring:
  cloud:
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: true
        discovery-server-url: ${DISCOVERY_SERVER_URL:http://spring-cloud-kubernetes-discoveryserver:80}