server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: "catalog"
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/catalogdb}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  redis:
    host: ${SPRING_DATA_REDIS_HOST:localhost}
    port: ${SPRING_DATA_REDIS_PORT:6379}
    password: ${SPRING_DATA_REDIS_PASSWORD:}
  cache:
    type: redis
  grpc:
    server:
      port: ${GRPC_SERVER_PORT:9090}
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
