server:
  port: 8080
spring:
  application:
    name: "catalog"
  datasource:
    url: "jdbc:postgresql://localhost:5432/catalogdb"
    username: admin
    password: admin
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
  grpc:
    server:
      port: 9090
management:
  endpoints:
    web:
      exposure:
        include: "*"
