server:
  port: 8072

spring:
  application:
    name: gatewayserver

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
    gateway:
      access: unrestricted
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
    instances:
      coursesCircuitBreaker:
        baseConfig: default
  timelimiter:
    instances:
      coursesCircuitBreaker:
        timeoutDuration: 5s