server:
  port: 8072

spring:
  application:
    name: gatewayserver

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
    gateway:
      access: unrestricted
