server:
  port: ${SERVER_PORT:8070}
spring:
  application:
    name: "payment"
  grpc:
    client:
      channels:
        order:
          address: ${ORDER_GRPC_ADDR:0.0.0.0:9091}
          negotiationType: ${ORDER_GRPC_NEGOTIATION:PLAINTEXT}
  kafka:
    bootstrap-servers: ${BOOTSTRAP-SERVERS-KAFKA:localhost:9094}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true